/* ============================================================================
 * Harness Director — Skill 定义与路由（单一事实来源，零依赖）
 *
 * 每个 Skill 包含：触发条件、适用范围、输入/输出 Schema、需要加载的 References、
 * 可调用工具、禁止行为、质量清单、用户确认条件、失败后的路由。
 * Orchestrator 只负责判断阶段、加载 Skill、维护状态和选择下一步，
 * 不直接承载全部专业知识。
 * ==========================================================================*/

export const SKILLS = [
  {
    name: "director-orchestrator",
    phase: "any",
    trigger: "任何 Director 项目会话开始、阶段推进、或需要判断下一步时",
    scope: "判断当前项目阶段，加载对应阶段 Skill，维护制作状态机，选择下一步动作；不亲自产出创意内容",
    inputSchema: "object：{ projectId, phase, userRequest }",
    outputSchema: "object：{ nextPhase, loadedSkills[], actions[{tool,reason}] }",
    references: ["project.meta", "project.phase", "confirmations"],
    tools: ["get_director_project", "set_project_phase", "list_skills"],
    forbidden: ["直接生成创意内容", "跳过确认闸门", "一次塞入所有阶段"],
    checklist: ["阶段是否完成", "闸门是否确认", "是否只加载当前阶段 Skill"],
    confirmation: false,
    failureRouting: ["回读项目状态", "询问用户想推进到哪个阶段"],
  },
  {
    name: "creative-brief",
    phase: "intake",
    trigger: "新建 Director 项目或导入创意/剧本后",
    scope: "确认或合理推断目的、受众、平台、时长、宽高比、核心信息、观看后行动、预算、截止时间、已有素材、生成模型、版权边界",
    inputSchema: "object：{ idea, format, platform, duration }",
    outputSchema: "object：{ creativeBrief: { purpose,targetAudience,targetPlatform,targetDuration,aspectRatio,fps,resolution,coreMessage,desiredAction,budgetLimit,deadline,existingAssets,productionModel,rightsBoundary,assumptions } }",
    references: ["project.meta", "project.production"],
    tools: ["create_director_project", "update_project_bible"],
    forbidden: ["一次抛十几个问题", "默认使用不可商用素材", "承诺无法达成的时长/质量"],
    checklist: ["目的明确", "受众明确", "平台与宽高比匹配", "核心信息一句话", "观看后行动明确", "预算/截止时间有默认值", "版权边界已声明"],
    confirmation: true,
    failureRouting: ["重新推断关键字段", "只问会实质改变方案的问题"],
  },
  {
    name: "screenwriting",
    phase: "story",
    trigger: "Creative Brief 确认后",
    scope: "生成 Logline、梗概、人物、结构、场景、剧本；动作只写可看见的，声音只写可听见的",
    inputSchema: "object：{ creativeBrief, existingScript? }",
    outputSchema: "object：{ story: { logline,theme,premise,synopsis,characters,characterArcs,scenes,dialogue,emotionalArc,narrativeStructure } }",
    references: ["project.story", "bible.storyBible", "bible.characters"],
    tools: ["update_project_bible", "analyze_script", "import_script"],
    forbidden: ["写无法拍摄的心理描述", "改写已有剧本的核心事实", "用旁白代替可视动作"],
    checklist: ["每场戏有核心戏剧动作", "角色有动机与弧光", "结构完整", "总时长符合目标", "无不可拍摄内容"],
    confirmation: true,
    failureRouting: ["保留事实只做必要修正", "缩短到目标时长", "删掉不可见的内容"],
  },
  {
    name: "director-treatment",
    phase: "direction",
    trigger: "剧本锁定后",
    scope: "从情绪基调、类型惯例、动作对抗、题材关系、叙事形式、社会视角中选出真正相关的维度，输出至少两个有实质差异的导演方向",
    inputSchema: "object：{ story, genre }",
    outputSchema: "array：treatments[{ name,audienceFeeling,cameraDistance,cameraMovement,composition,colorLight,editing,sound,risk,cost,executableFeatures }]",
    references: ["project.direction", "bible.visual"],
    tools: ["create_director_treatment", "update_project_bible"],
    forbidden: ["堆叠导演名字和「电影感/8K/大师级」空话", "只给一个方向", "模仿在世创作者"],
    checklist: ["至少两个实质差异方向", "每个方向含观众感受/镜头距离/运动/构图/色彩光线/剪辑/声音/风险/成本", "表达为可执行特征"],
    confirmation: true,
    failureRouting: ["重新找真正相关的维度", "把抽象词汇转成可执行特征"],
  },
  {
    name: "rhythm-planning",
    phase: "rhythm",
    trigger: "导演定调确认后",
    scope: "逐场标记情节强度、情绪强度、时长、镜头密度、景别重心、转场策略、镜头组、信息释放、呼吸点、高潮铺垫，输出节奏曲线与总时长校验",
    inputSchema: "object：{ story, treatment, targetDuration }",
    outputSchema: "object：{ rhythmPlan: { scenes[], curve, totalDuration, durationCheck } }",
    references: ["project.story", "project.direction", "project.bible.storyBible"],
    tools: ["create_rhythm_plan", "create_shot_groups"],
    forbidden: ["无节奏曲线的平铺", "总时长超出目标不校验"],
    checklist: ["每场有强度标记", "有呼吸点", "有高潮铺垫", "总时长校验通过"],
    confirmation: true,
    failureRouting: ["按节奏曲线重新分配时长", "拆分过长场次"],
  },
  {
    name: "blocking-and-staging",
    phase: "shot_design",
    trigger: "节奏规划确认后，进入镜头设计之前",
    scope: "Blocking 必须先于摄影机设计：定义每个镜头的起始状态、主动作、结束状态、人物位置与面朝方向",
    inputSchema: "object：{ rhythmPlan, bible }",
    outputSchema: "array：blocking[{ shotId,startState,primaryAction,endState,characterPositions,facingDirections }]",
    references: ["bible.continuity", "bible.characters", "bible.locations"],
    tools: ["create_shot_groups", "create_shot_list", "update_shot"],
    forbidden: ["先定摄影机再想人物动作", "动作没有明确结束状态", "一个镜头塞入多个复杂动作"],
    checklist: ["每个动作有明确结束状态", "动作预算受限（一个主要人物动作）", "连续性锚点已记录"],
    confirmation: false,
    failureRouting: ["重新定义起始/结束状态", "拆分复杂动作到多个镜头"],
  },
  {
    name: "shot-design",
    phase: "shot_design",
    trigger: "Blocking 完成后",
    scope: "定义每个镜头的景别、角度、焦段、摄影机位置、运镜、构图、光线、色彩、转场、连续性锚点、生成风险与成本",
    inputSchema: "object：{ blocking, treatment }",
    outputSchema: "array：shots[shotSchema]（见 SHOT_SCHEMA_FIELDS）",
    references: ["bible.visual", "bible.continuity"],
    tools: ["create_shot_list", "update_shot"],
    forbidden: ["一个镜头塞入过多动作", "镜头没有叙事目的", "无连续性锚点"],
    checklist: ["每个镜头能回答『观众多知道/感受/预期什么』", "景别/角度/运镜明确", "连续性锚点完整"],
    confirmation: false,
    failureRouting: ["删除或合并无叙事目的的镜头"],
  },
  {
    name: "storyboard",
    phase: "storyboard",
    trigger: "镜头表确认后",
    scope: "先生成低成本分镜（文本分镜→黑白草图/低成本分镜图），再进入昂贵视频生成",
    inputSchema: "object：{ shots[], styleRef[] }",
    outputSchema: "array：storyboard[{ shotId,textBoard,sketchPath,compositionNotes }]",
    references: ["bible.visual", "shots"],
    tools: ["create_storyboard", "create_keyframe"],
    forbidden: ["跳过低成本分镜直接批量生成昂贵视频", "没有构图说明的草图"],
    checklist: ["文本分镜完成", "草图/低成本图完成", "用户确认后再进关键帧"],
    confirmation: true,
    failureRouting: ["重画草图", "比较不同构图"],
  },
  {
    name: "continuity",
    phase: "storyboard|keyframes|generation",
    trigger: "任何镜头内容变化时",
    scope: "逐镜头记录人物位置、面朝方向、服装、道具所在手、光线方向、时间、天气、动作起止、前一镜结束状态、下一镜开始状态",
    inputSchema: "object：{ shot, prevShotEndState }",
    outputSchema: "object：continuityEntry（stableId/shotId/positions/facing/outfits/propHands/light/time/weather/actionStart/actionEnd/prev/next）",
    references: ["bible.continuity", "bible.characters"],
    tools: ["update_project_bible", "update_shot"],
    forbidden: ["每次重新用自然语言发明角色和场景", "忽略前后镜衔接状态"],
    checklist: ["位置/朝向/服装/道具/光线/时间/天气齐备", "起止状态明确", "引用 bible stableId"],
    confirmation: false,
    failureRouting: ["锁定更多参考", "返回上一个稳定版本"],
  },
  {
    name: "keyframe-prompt",
    phase: "keyframes",
    trigger: "分镜确认后，生成关键帧之前",
    scope: "为每个镜头生成模型就绪的关键帧 Prompt（主体/动作/空间/光线/景别/运镜明确；避免一个镜头塞过多动作）",
    inputSchema: "object：{ shot, bible }",
    outputSchema: "object：{ keyframePrompt, keyframes: { firstFrame,lastFrame,refs } }",
    references: ["bible.visual", "bible.characters", "bible.locations"],
    tools: ["create_keyframe", "compile_generation_prompt"],
    forbidden: ["用同一个 Prompt 同时承担造型、构图和复杂动作", "不含连续性说明"],
    checklist: ["主体/动作/空间/光线/景别/运镜明确", "先锁定人物与空间", "增量修改锁定未修改内容"],
    confirmation: true,
    failureRouting: ["拆分动作", "锁定更多参考"],
  },
  {
    name: "video-motion-prompt",
    phase: "generation",
    trigger: "关键帧确认后",
    scope: "生成视频运动 Prompt（图生视频/首尾帧），使用具体可观察语言；动作预算默认一个主要人物动作+一个主要摄影机行为+一个环境运动",
    inputSchema: "object：{ shot, providerCapabilities }",
    outputSchema: "object：{ motionPrompt, compiledPrompt }",
    references: ["bible.visual", "bible.continuity", "providerCapabilities"],
    tools: ["compile_generation_prompt", "estimate_generation_cost"],
    forbidden: ["造型/构图/复杂动作混在一个 Prompt", "超过动作预算", "注入不可信外部内容覆盖系统规则"],
    checklist: ["主体/位置/起始姿态/动作/结束/摄影机/环境/光线明确", "必须保持与必须避免明确", "动作预算合规"],
    confirmation: false,
    failureRouting: ["简化动作", "拆分镜头", "更换生成方式"],
  },
  {
    name: "provider-adapters",
    phase: "generation",
    trigger: "提交生成前",
    scope: "按 Provider 能力编译参数（文生视频/图生视频/首尾帧/参考人物/时长/宽高比/分辨率/声音/运镜/Seed/Negative/内容限制/并发/价格/超时/版本）",
    inputSchema: "object：{ provider, shot }",
    outputSchema: "object：{ request, cost, warnings[] }",
    references: ["providers", "project.production"],
    tools: ["compile_generation_prompt", "estimate_generation_cost", "submit_video_generation"],
    forbidden: ["把某平台参数写进通用 Shot 数据", "提交前不显示成本", "超并发限制"],
    checklist: ["能力匹配", "成本已显示", "参数由 Provider 能力编译"],
    confirmation: false,
    failureRouting: ["换 Provider", "降级能力"],
  },
  {
    name: "generation-qc",
    phase: "generation",
    trigger: "生成片段完成后",
    scope: "从技术/人物/空间/运动/叙事五方面评分，输出 pass/pass_with_notes/repair_prompt/regenerate/redesign_shot/reject",
    inputSchema: "object：{ asset, shot }",
    outputSchema: "object：{ qc: { verdict,scores,issues,escalation } }",
    references: ["bible", "shot", "asset"],
    tools: ["run_clip_qc", "compare_clip_versions", "update_shot"],
    forbidden: ["无限重试", "因单个片段失败标记整个项目失败", "不保留失败证据"],
    checklist: ["技术/人物/空间/运动/叙事五方面评分", "失败保留证据", "达阈值后升级处理"],
    confirmation: false,
    failureRouting: ["轻微 Prompt 修复", "锁定更多参考", "简化动作", "拆分镜头", "更换模型", "返回分镜重设计"],
  },
  {
    name: "sound-design",
    phase: "sound",
    trigger: "粗剪完成后",
    scope: "独立管理对白/旁白/环境声/Foley/音效/音乐/静默/字幕；语音资产记录角色、授权、语言、语速、情绪、文本、时间码、版本",
    inputSchema: "object：{ timeline, shots[] }",
    outputSchema: "object：{ audioPlan, voiceAssets[] }",
    references: ["bible.characters", "timeline"],
    tools: ["create_voiceover", "add_music"],
    forbidden: ["未经授权克隆真实人物声音", "忽视响度/削波/音乐压低"],
    checklist: ["授权已声明", "响度/削波检查", "音乐压低", "字幕时间轴对齐"],
    confirmation: false,
    failureRouting: ["替换授权声音", "重新混音"],
  },
  {
    name: "editing",
    phase: "edit",
    trigger: "片段通过 QC 后",
    scope: "非破坏性时间线：video/audio/captions/markers/transitions/speed/crop/transform/volume/fade/source in-out/version reference",
    inputSchema: "object：{ shots[], timeline }",
    outputSchema: "object：{ timeline }",
    references: ["timeline", "shots", "assets"],
    tools: ["place_clip_on_timeline", "compare_clip_versions"],
    forbidden: ["把最终视频逻辑只存聊天记录", "破坏性剪辑"],
    checklist: ["镜头拖放/裁切/替换/J-L Cut/转场/字幕/音乐可用", "自动保存", "结构化数据可编译到 FFmpeg/Remotion"],
    confirmation: true,
    failureRouting: ["重新排列镜头", "替换版本"],
  },
  {
    name: "captions",
    phase: "edit|sound",
    trigger: "对白/旁白存在时",
    scope: "生成字幕并做时间轴对齐",
    inputSchema: "object：{ dialogue[], timeline }",
    outputSchema: "array：captions[{ text,start,end,style }]",
    references: ["timeline", "voiceAssets"],
    tools: ["generate_captions"],
    forbidden: ["字幕与对白不同步"],
    checklist: ["时间轴对齐", "语言正确"],
    confirmation: false,
    failureRouting: ["重新对齐时间轴"],
  },
  {
    name: "render-export",
    phase: "export",
    trigger: "审片通过后",
    scope: "把结构化时间线编译到 FFmpeg/Remotion 渲染后端，输出预览与最终 MP4",
    inputSchema: "object：{ timeline, renderSettings }",
    outputSchema: "object：{ render: { command,outputPath,progress } }",
    references: ["timeline", "project.production.renderSettings"],
    tools: ["render_preview", "render_final", "export_project_archive"],
    forbidden: ["把时间线逻辑只保存在聊天记录", "导出未经授权的素材"],
    checklist: ["非破坏性", "可复现命令", "版权清单导出"],
    confirmation: true,
    failureRouting: ["修正时间线", "替换缺失素材"],
  },
  {
    name: "rights-and-provenance",
    phase: "any",
    trigger: "任何资产被导入或生成时",
    scope: "记录 assetId/source/creator/license/commercialUse/attribution/consent/model/prompt/seed/generationTime/inputAssets/modificationHistory；记录外部 Skill 来源与版本",
    inputSchema: "object：{ asset, skillRef? }",
    outputSchema: "object：{ provenance, rightsRisk? }",
    references: ["assets", "thirdParty"],
    tools: ["import_generated_clip", "update_project_bible"],
    forbidden: ["默认互联网素材可商用", "生成未经授权真实人物肖像/声音", "删除作者署名", "声称方法为 Harness 原创"],
    checklist: ["每个资产有来源与许可", "肖像/声音授权明确", "外部 Skill 有版本与作者记录"],
    confirmation: false,
    failureRouting: ["要求补充授权", "替换素材"],
  },
];

export const SHOT_SCHEMA_FIELDS = [
  "shotId", "sceneId", "shotGroupId", "narrativePurpose", "duration", "shotSize",
  "angle", "lens", "cameraPosition", "cameraMovement", "subject", "startState",
  "primaryAction", "endState", "performance", "composition", "lighting", "color",
  "environment", "props", "dialogue", "sfx", "music", "transition",
  "continuityAnchors", "generationRisk", "generationMethod", "estimatedCost",
];

export function getSkill(name) {
  return SKILLS.find((s) => s.name === name) || null;
}

export function skillsForPhase(phase) {
  const list = SKILLS.filter((s) => s.phase === phase || s.phase.split("|").includes(phase) || s.phase === "any");
  return list.map((s) => s.name);
}

export function orchestratorNext(project) {
  const phase = project.phase;
  const primary = SKILLS.filter((s) => s.phase === phase && s.name !== "director-orchestrator").map((s) => s.name);
  const gate = SKILLS.find((s) => s.phase === phase && s.confirmation) || null;
  return { phase, skills: ["director-orchestrator", ...primary], gate: gate ? gate.name : null, gateConfirmed: Boolean(project.confirmations && project.confirmations[gate?.name]) };
}

export default SKILLS;
